Use LESS "1.3.x" instead of ">= 1.3.0"
LESS 1.4.0 (beta) produces a unexpected error 

    Running "recess:build" (recess) task
    >> TypeError: Cannot call method 'map' of undefined

Producing all packages depending on recess to fail.

Related: https://github.com/twitter/bootstrap/issues/8088